name: immobilier_app
description: Application Flutter pour la gestion d'annonces immobilières avec GetX

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  # carousel_slider: ^4.2.1  # Conflit avec Flutter 3.29+
  page_view_indicators: ^2.0.0
  photo_view: ^0.14.0
  
  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.3+1
  path_provider: ^2.1.2
  
  # Storage
  shared_preferences: ^2.2.3
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.6
  image_picker: ^1.0.8
  share_plus: ^7.2.1
  
  # Forms & Validation
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^11.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700

